### ISSUE TITLE
Question about densification

### ISSUE THREAD

**Issue by Gynjn** [GVGEN/GVGEN#1]
First, Thanks for sharing your great work.

BTW, I have some confusing point in the text.

1) When you select the newly added point from the pool, the criterion is the (static xyz) location or the (xyz + offset) location in the pool? And also is it right the distance is compared with the (xyz + offset) location of the "gonna densified"  points?

2) "The corresponding coordinate offsets for the added points are calculated" is meaning that the new offset is calculated like distance between the "static xyz" point retrieved from the pool and the "gonna densified" points location (static xyz + offset)?

3) Except for the position, the other feature is initialized from the one's in candidate pool? or using the "gonna densified" features?

Thanks.

**Comment by GVGEN** [comment]
Hi, thanks for your interest in our work!
The candidate pool stores grid points in the volume, whose coordinates is fixed (static xyz). So, for your questions:
We first compute the positions (`new_xyz`) of newly added Gaussians, and select the nearest "deactivated" grid points (whose positions are `xyz`) from the pool. After that, we set the positions and offsets of Gaussians as (`xyz` and `new_xyz - xyz`).
The other features of newly added Gaussians are initialized as the same as the original 3DGS (func `densify_and_split` and `densify_and_clone`).
